/**
 * Onboarding Workflow Triggers
 *
 * Handles automations for onboarding checklist items:
 * - Down Payment Received = No → creates case "Sales Action is Required for Money Hold"
 * - Deductible Received = No → creates case "Sales Action is Required for Money Hold"
 * - Estimate Received = No → creates case "Sales Action is Required"
 *
 * These replicate the Salesforce PandaClaims review workflow.
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Case types for onboarding issues
const CASE_TYPES = {
  MONEY_HOLD: 'Sales Action Required',
  ESTIMATE_REQUIRED: 'Sales Action Required',
};

// Case subjects
const CASE_SUBJECTS = {
  DOWN_PAYMENT_HOLD: 'Sales Action is Required for Money Hold - Down Payment Not Received',
  DEDUCTIBLE_HOLD: 'Sales Action is Required for Money Hold - Deductible Not Received',
  ESTIMATE_REQUIRED: 'Sales Action is Required - Estimate Not Received',
};

/**
 * Generate the next case number
 */
async function generateCaseNumber() {
  const lastCase = await prisma.case.findFirst({
    orderBy: { createdAt: 'desc' },
    select: { caseNumber: true },
  });

  let nextNumber = 1;
  if (lastCase?.caseNumber) {
    const match = lastCase.caseNumber.match(/CASE-(\d+)/);
    if (match) {
      nextNumber = parseInt(match[1]) + 1;
    }
  }
  return `CASE-${String(nextNumber).padStart(6, '0')}`;
}

/**
 * Create a case for an opportunity
 */
async function createOnboardingCase(opportunityId, subject, description, type, userId) {
  try {
    // Get opportunity details
    const opportunity = await prisma.opportunity.findUnique({
      where: { id: opportunityId },
      include: {
        account: true,
        owner: true,
      },
    });

    if (!opportunity) {
      throw new Error(`Opportunity not found: ${opportunityId}`);
    }

    // Check if a similar case already exists and is open
    const existingCase = await prisma.case.findFirst({
      where: {
        accountId: opportunity.accountId,
        subject: subject,
        status: { in: ['NEW', 'WORKING', 'ESCALATED'] },
      },
    });

    if (existingCase) {
      console.log(`[Onboarding Trigger] Case already exists for ${subject}: ${existingCase.id}`);
      return { existing: true, case: existingCase };
    }

    const caseNumber = await generateCaseNumber();

    const newCase = await prisma.case.create({
      data: {
        caseNumber,
        subject,
        description: `${description}\n\nOpportunity: ${opportunity.name}\nJob ID: ${opportunity.jobId || 'N/A'}\n\nThis case was auto-generated by the onboarding workflow.`,
        accountId: opportunity.accountId,
        priority: 'HIGH',
        type: type,
        status: 'NEW',
        origin: 'WORKFLOW',
      },
    });

    console.log(`[Onboarding Trigger] Created case: ${newCase.caseNumber} - ${subject}`);

    // Create activity log
    await prisma.activity.create({
      data: {
        type: 'CASE_CREATED',
        subject: `Case Created: ${subject}`,
        body: `Auto-generated case for onboarding issue.\nCase Number: ${caseNumber}`,
        status: 'COMPLETED',
        opportunityId: opportunityId,
        accountId: opportunity.accountId,
        userId: userId,
        occurredAt: new Date(),
        metadata: {
          triggeredBy: 'onboarding_workflow',
          autoGenerated: true,
          caseId: newCase.id,
          caseNumber: caseNumber,
        },
      },
    });

    return { existing: false, case: newCase };
  } catch (error) {
    console.error(`[Onboarding Trigger] Failed to create case:`, error);
    throw error;
  }
}

/**
 * Trigger: Down Payment Not Received
 * When downPaymentReceived is set to false, create a money hold case
 */
export async function onDownPaymentNotReceived(opportunityId, userId) {
  console.log(`[Onboarding Trigger] Down Payment Not Received for Opportunity: ${opportunityId}`);

  const result = {
    case: null,
    error: null,
  };

  try {
    const caseResult = await createOnboardingCase(
      opportunityId,
      CASE_SUBJECTS.DOWN_PAYMENT_HOLD,
      'The down payment has not been received for this opportunity. Sales action is required to resolve the money hold.',
      CASE_TYPES.MONEY_HOLD,
      userId
    );

    result.case = caseResult.case;
    result.wasExisting = caseResult.existing;

    return result;
  } catch (error) {
    console.error('[Onboarding Trigger] onDownPaymentNotReceived failed:', error);
    result.error = error.message;
    return result;
  }
}

/**
 * Trigger: Deductible Not Received
 * When deductibleReceived is set to false, create a money hold case
 */
export async function onDeductibleNotReceived(opportunityId, userId) {
  console.log(`[Onboarding Trigger] Deductible Not Received for Opportunity: ${opportunityId}`);

  const result = {
    case: null,
    error: null,
  };

  try {
    const caseResult = await createOnboardingCase(
      opportunityId,
      CASE_SUBJECTS.DEDUCTIBLE_HOLD,
      'The deductible has not been received for this opportunity. Sales action is required to resolve the money hold.',
      CASE_TYPES.MONEY_HOLD,
      userId
    );

    result.case = caseResult.case;
    result.wasExisting = caseResult.existing;

    return result;
  } catch (error) {
    console.error('[Onboarding Trigger] onDeductibleNotReceived failed:', error);
    result.error = error.message;
    return result;
  }
}

/**
 * Trigger: Estimate Not Received
 * When estimateReceived is set to false, create a sales action case
 */
export async function onEstimateNotReceived(opportunityId, userId) {
  console.log(`[Onboarding Trigger] Estimate Not Received for Opportunity: ${opportunityId}`);

  const result = {
    case: null,
    error: null,
  };

  try {
    const caseResult = await createOnboardingCase(
      opportunityId,
      CASE_SUBJECTS.ESTIMATE_REQUIRED,
      'The estimate has not been received for this opportunity. Sales action is required to obtain the estimate.',
      CASE_TYPES.ESTIMATE_REQUIRED,
      userId
    );

    result.case = caseResult.case;
    result.wasExisting = caseResult.existing;

    return result;
  } catch (error) {
    console.error('[Onboarding Trigger] onEstimateNotReceived failed:', error);
    result.error = error.message;
    return result;
  }
}

/**
 * Main handler to evaluate and execute onboarding triggers based on opportunity changes
 *
 * This function is called when opportunity onboarding fields are updated.
 * It checks if any checklist items were explicitly set to false and triggers
 * the appropriate case creation.
 *
 * @param {string} opportunityId - The opportunity ID
 * @param {object} changes - The changes made to the opportunity
 * @param {boolean} changes.downPaymentReceived - Down payment received status
 * @param {boolean} changes.deductibleReceived - Deductible received status
 * @param {boolean} changes.estimateReceived - Estimate received status
 * @param {string} userId - The user who made the changes
 */
export async function evaluateOnboardingTriggers(opportunityId, changes, userId) {
  const results = [];

  // Check for down payment not received
  // Trigger when explicitly set to false (not just undefined)
  if (changes.downPaymentReceived === false) {
    const result = await onDownPaymentNotReceived(opportunityId, userId);
    results.push({ trigger: 'downPaymentNotReceived', result });
  }

  // Check for deductible not received
  if (changes.deductibleReceived === false) {
    const result = await onDeductibleNotReceived(opportunityId, userId);
    results.push({ trigger: 'deductibleNotReceived', result });
  }

  // Check for estimate not received
  if (changes.estimateReceived === false) {
    const result = await onEstimateNotReceived(opportunityId, userId);
    results.push({ trigger: 'estimateNotReceived', result });
  }

  return results;
}

export default {
  onDownPaymentNotReceived,
  onDeductibleNotReceived,
  onEstimateNotReceived,
  evaluateOnboardingTriggers,
  CASE_TYPES,
  CASE_SUBJECTS,
};
