/**
 * Specs Preparation Workflow Triggers
 *
 * Handles automations for specs preparation workflow:
 * - When specsPrepped = true, update opportunity status and create Contract Signing records
 * - Replicates Salesforce's Create_WOLI_on_Spec_Autolaunch_flow behavior
 *
 * ScribeHow Reference: Insurance_Sales__Preparing_the_specs
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Work type for contract signing
const CONTRACT_SIGNING_WORK_TYPE = 'Contract Signing';

/**
 * Trigger: Specs Preparation Complete
 * When an opportunity's specsPrepped field changes to true
 *
 * Actions:
 * 1. Update opportunity status/disposition to "Specs Prepped"
 * 2. Create activity log entry
 * 3. Find or create WorkOrder for this opportunity
 * 4. Create WorkOrderLineItem for "Contract Signing" work type (like Salesforce WOLI)
 * 5. Create Service Appointment for "Contract Signing" (for scheduling)
 */
export async function onSpecsPrepped(opportunityId, specsData, userId) {
  console.log(`[Specs Trigger] Specs Prepped for Opportunity: ${opportunityId}`);

  const results = {
    opportunityUpdated: false,
    activityCreated: null,
    workOrder: null,
    workOrderLineItem: null,
    serviceAppointment: null,
    errors: [],
  };

  try {
    // Get opportunity details
    const opportunity = await prisma.opportunity.findUnique({
      where: { id: opportunityId },
      include: {
        account: true,
        contact: true,
        owner: true,
      },
    });

    if (!opportunity) {
      throw new Error(`Opportunity not found: ${opportunityId}`);
    }

    // 1. Update opportunity status to "Specs Prepped"
    try {
      await prisma.opportunity.update({
        where: { id: opportunityId },
        data: {
          specsPrepped: true,
          specsPrepDate: new Date(),
          specsData: specsData ? JSON.stringify(specsData) : null,
          status: 'Specs Prepped',
          // Don't overwrite stageName as it may be set by other workflows
          updatedAt: new Date(),
        },
      });
      results.opportunityUpdated = true;
      console.log(`[Specs Trigger] Updated opportunity status to "Specs Prepped"`);
    } catch (updateError) {
      console.error('[Specs Trigger] Failed to update opportunity:', updateError);
      results.errors.push({ type: 'opportunity_update', error: updateError.message });
    }

    // 2. Create Activity Log
    try {
      const activity = await prisma.activity.create({
        data: {
          type: 'WORKFLOW_TRIGGERED',
          subject: 'Specs Preparation Completed',
          body: `Project specifications have been prepared for ${opportunity.name}.\n\nThe project is now ready for contract signing.`,
          status: 'COMPLETED',
          opportunityId: opportunityId,
          accountId: opportunity.accountId,
          contactId: opportunity.contactId,
          userId: opportunity.ownerId || userId,
          occurredAt: new Date(),
          metadata: {
            triggeredBy: 'specs_prepped',
            autoGenerated: true,
            specsDataSummary: specsData ? Object.keys(specsData) : null,
          },
        },
      });
      results.activityCreated = activity;
      console.log(`[Specs Trigger] Created activity: ${activity.id}`);
    } catch (activityError) {
      console.error('[Specs Trigger] Failed to create activity:', activityError);
      results.errors.push({ type: 'activity', error: activityError.message });
    }

    // 3. Find or create Work Order for this opportunity
    try {
      let workOrder = await prisma.workOrder.findFirst({
        where: { opportunityId: opportunityId },
      });

      if (!workOrder) {
        // Generate work order number
        const lastWO = await prisma.workOrder.findFirst({
          orderBy: { createdAt: 'desc' },
          select: { workOrderNumber: true },
        });

        let nextNumber = 1;
        if (lastWO?.workOrderNumber) {
          const match = lastWO.workOrderNumber.match(/WO-(\d+)/);
          if (match) {
            nextNumber = parseInt(match[1], 10) + 1;
          }
        }

        workOrder = await prisma.workOrder.create({
          data: {
            workOrderNumber: `WO-${String(nextNumber).padStart(6, '0')}`,
            opportunityId: opportunityId,
            accountId: opportunity.accountId,
            subject: `Work Order - ${opportunity.name}`,
            status: 'NEW',
            priority: 'NORMAL',
          },
        });
        console.log(`[Specs Trigger] Created work order: ${workOrder.id}`);
      }

      results.workOrder = workOrder;

      // 4. Get the "Contract Signing" work type
      const workType = await prisma.workType.findFirst({
        where: {
          OR: [
            { name: CONTRACT_SIGNING_WORK_TYPE },
            { name: { contains: 'Contract Signing', mode: 'insensitive' } },
            { name: { contains: 'Contract', mode: 'insensitive' } },
          ],
        },
      });

      // Get territory (from account state if available)
      let territory = null;
      if (opportunity.state || opportunity.account?.billingState) {
        territory = await prisma.serviceTerritory.findFirst({
          where: {
            OR: [
              { name: { contains: opportunity.state || opportunity.account?.billingState, mode: 'insensitive' } },
              { state: opportunity.state || opportunity.account?.billingState },
            ],
          },
        });
      }

      // 5. Create WorkOrderLineItem (replicates Salesforce WOLI)
      const lastWOLI = await prisma.workOrderLineItem.findFirst({
        orderBy: { createdAt: 'desc' },
        select: { lineItemNumber: true },
      });

      let nextWOLINumber = 1;
      if (lastWOLI?.lineItemNumber) {
        const match = lastWOLI.lineItemNumber.match(/WOLI-(\d+)/);
        if (match) {
          nextWOLINumber = parseInt(match[1], 10) + 1;
        }
      }

      const workOrderLineItem = await prisma.workOrderLineItem.create({
        data: {
          lineItemNumber: `WOLI-${String(nextWOLINumber).padStart(6, '0')}`,
          workOrderId: workOrder.id,
          workTypeId: workType?.id,
          opportunityId: opportunityId,
          territoryId: territory?.id,
          description: `Contract Signing for ${opportunity.name} - Specs preparation complete`,
          status: 'NEW',
          duration: 60, // 1 hour default
        },
      });
      results.workOrderLineItem = workOrderLineItem;
      console.log(`[Specs Trigger] Created WorkOrderLineItem: ${workOrderLineItem.id}`);

      // 6. Create Service Appointment for scheduling
      const lastAppt = await prisma.serviceAppointment.findFirst({
        orderBy: { createdAt: 'desc' },
        select: { appointmentNumber: true },
      });

      let nextApptNumber = 1;
      if (lastAppt?.appointmentNumber) {
        const match = lastAppt.appointmentNumber.match(/SA-(\d+)/);
        if (match) {
          nextApptNumber = parseInt(match[1], 10) + 1;
        }
      }

      // Schedule for 3 days from now, 1 hour duration
      const scheduledStart = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000);
      const scheduledEnd = new Date(scheduledStart.getTime() + 60 * 60 * 1000);

      const serviceAppointment = await prisma.serviceAppointment.create({
        data: {
          appointmentNumber: `SA-${String(nextApptNumber).padStart(6, '0')}`,
          workOrderId: workOrder.id,
          workTypeId: workType?.id,
          subject: `Contract Signing - ${opportunity.name}`,
          description: 'Schedule contract signing appointment with homeowner. Specs preparation is complete.',
          status: 'NONE',
          street: opportunity.street || opportunity.account?.billingStreet,
          city: opportunity.city || opportunity.account?.billingCity,
          state: opportunity.state || opportunity.account?.billingState,
          postalCode: opportunity.postalCode || opportunity.account?.billingPostalCode,
          earliestStart: new Date(),
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
          duration: 60, // minutes
        },
      });

      results.serviceAppointment = serviceAppointment;
      console.log(`[Specs Trigger] Created service appointment: ${serviceAppointment.id}`);

    } catch (workOrderError) {
      console.error('[Specs Trigger] Failed to create work order/WOLI/appointment:', workOrderError);
      results.errors.push({ type: 'work_order', error: workOrderError.message });
    }

    return results;

  } catch (error) {
    console.error('[Specs Trigger] onSpecsPrepped failed:', error);
    throw error;
  }
}

/**
 * Evaluate specs triggers based on opportunity changes
 * Called when opportunity is updated with specsPrepped = true
 */
export async function evaluateSpecsTriggers(opportunityId, changes, userId) {
  const results = [];

  // Check if specs were just prepped
  if (changes.specsPrepped === true && changes._previousSpecsPrepped !== true) {
    const result = await onSpecsPrepped(opportunityId, changes.specsData, userId);
    results.push({ trigger: 'specsPrepped', result });
  }

  return results;
}

export default {
  onSpecsPrepped,
  evaluateSpecsTriggers,
  CONTRACT_SIGNING_WORK_TYPE,
};
